# day12

In [1]:
import numpy as np

In [2]:
list1 = [[12,24,56],[12,13,8],[6,5,10]]

In [3]:
arr = np.array(list1)

In [4]:
arr

array([[12, 24, 56],
       [12, 13,  8],
       [ 6,  5, 10]])

In [7]:
asc_sor_col = np.sort(arr,axis=0)
asc_sor_col

array([[ 6,  5,  8],
       [12, 13, 10],
       [12, 24, 56]])

In [8]:
asc_sor_row= np.sort(arr,axis=1)
asc_sor_row

array([[12, 24, 56],
       [ 8, 12, 13],
       [ 5,  6, 10]])

In [10]:
nw = np.array([asc_sor_col[0,1],asc_sor_col[1,0],asc_sor_col[2,2]])

In [11]:
nw

array([ 5, 12, 56])

In [38]:
rng = np.random.default_rng(seed = 44)
k = rng.integers(-100,100,(3,3))
k

array([[ 33, -76,  63],
       [-49,  33, -19],
       [-83,  93,   6]], dtype=int64)

In [39]:
b = np.where(k < 0)
k[b] = 0
r = k

In [40]:
r

array([[33,  0, 63],
       [ 0, 33,  0],
       [ 0, 93,  6]], dtype=int64)

In [57]:
#another method directly by where
b = np.where(k<0,0,k)

In [59]:
b

array([[33,  0, 63],
       [ 0, 33,  0],
       [ 0, 93,  6]], dtype=int64)

In [60]:
list1 =[[12,23,34,34],[12,12,20,21]]
ay = np.array(list1)

In [61]:
unq_ele,ele_count = np.unique(ay,return_counts=True)

In [63]:
print("unique elements:", unq_ele)

unique elements: [12 20 21 23 34]
