# day14

In [77]:
names = ["Kelly", "Ben", "Jack", "Mhammad", "Jose", "Liz"]
grades = [45,65,75,35,85,40]
classes = ["a","c","e","g","e","f"]

In [78]:
import numpy as np

In [79]:
arr = np.array([names,grades,classes])

In [80]:
arr

array([['Kelly', 'Ben', 'Jack', 'Mhammad', 'Jose', 'Liz'],
       ['45', '65', '75', '35', '85', '40'],
       ['a', 'c', 'e', 'g', 'e', 'f']], dtype='<U11')

In [87]:
name = np.array(arr[0,::])

In [88]:
name

array(['Kelly', 'Ben', 'Jack', 'Mhammad', 'Jose', 'Liz'], dtype='<U11')

In [89]:
marks = np.array(arr[1,::],dtype=int)

In [90]:
marks

array([45, 65, 75, 35, 85, 40])

In [91]:
grads = np.array(arr[2,::])

In [92]:
grads

array(['a', 'c', 'e', 'g', 'e', 'f'], dtype='<U11')

In [107]:
stud_nam = np.where(marks >50) and  np.where(grads == "e")
stud_nam 

(array([2, 4], dtype=int64),)

In [111]:
name[stud_nam]

array(['Jack', 'Jose'], dtype='<U11')

In [112]:
stud_mark_75 = np.where(marks<75)

In [113]:
name[stud_mark_75]

array(['Kelly', 'Ben', 'Mhammad', 'Liz'], dtype='<U11')

In [115]:
liz= np.where(name=='Liz')

In [116]:
marks[liz]

array([40])

In [117]:
high = np.argmax(marks)

In [118]:
high

4

In [119]:
name[high]

'Jose'

In [124]:
l_name = np.argmax(name)
l_name

3

In [121]:
name[l_name]

'Mhammad'

In [122]:
len(name[l_name])

7

In [ ]:
a