# day-1

In [ ]:
Write code to import NumPy into your script. Check the version of NumPy installed.  Here is a list below:  list1 = [2, 3, 4, 6] Create a one-dimensional array from the list above. Write another line of code to check the shape and size of your array. Write a function that takes this array and returns a new array with all the values in the original array reversed. list1 = [2, 3, 4, 6]  list2 = [8, 10, 12, 14]

Alexander, Benjamin. 50 Days of Data Analysis with Python: The Ultimate Challenges Book for Beginners: Hands-on Challenges with pandas, NumPy, Matplotlib, Sklearn and Seaborn (p. 64). Kin

Create an array from the two lists above. Then write code to check the shape, dimensions,  and data type of the array. list1 = [2, 3, 4, 6]  list2 = [8, 10.1, 12, 14] list3 = [16, 18, 20, 22.1] Create an array from the three (3) lists above. Take note that some of the lists contain floats. Create an array that will have an int64 data type. Is it possible to create an array of both floats and integers?

Alexander, Benjamin. 50 Days of Data Analysis with Python: The Ultimate Challenges Book for Beginners: Hands-on Challenges with pandas, NumPy, Matplotlib, Sklearn and Seaborn (p. 64). Kindle Edition. 

In [1]:
import numpy as np

In [2]:
version

NameError: name 'version' is not defined

In [3]:
np.v

AttributeError: module 'numpy' has no attribute 'v'

In [4]:
np.version

<module 'numpy.version' from 'C:\\Users\\Divyansh\\anaconda3\\Lib\\site-packages\\numpy\\version.py'>

In [5]:
np.__version__

'1.24.3'

In [8]:
list1 = [2, 3, 4, 6]

In [10]:
l1=np.array(list1)

In [11]:
l1 

array([2, 3, 4, 6])

In [12]:
l1.shape

(4,)

In [13]:
l1.size

4

In [14]:
def rev(arr):
    return arr[::-1]


In [15]:
rev(l1)

array([6, 4, 3, 2])

In [18]:
#another way to do it by using flip
rev_l=np.flip(l1,axis=None)
rev_l

array([6, 4, 3, 2])

In [24]:
li1=[2,3,4,6]
li2=[8,10,12,14]
arr_c=np.array([li1,li2])

In [25]:
arr_c

array([[ 2,  3,  4,  6],
       [ 8, 10, 12, 14]])

In [26]:
arr_c.shape


(2, 4)

In [27]:
arr_c.size


8

In [28]:
arr_c.dtype

dtype('int32')

In [29]:
arr_c.ndim


2

In [30]:
list1 = [2, 3, 4, 6]
list2 = [8, 10.1, 12, 14]
list3 = [16, 18, 20, 22.1]

a123=np.array([list1,list2,list3],dtype="int")

In [31]:
a123

array([[ 2,  3,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [32]:
a123=np.array([list1,list2,list3],dtype="float")

In [33]:
a123

array([[ 2. ,  3. ,  4. ,  6. ],
       [ 8. , 10.1, 12. , 14. ],
       [16. , 18. , 20. , 22.1]])