# day5

In [ ]:
Day 5: Array Creation and Vector Operations In this challenge, you will create a 2-dimensional array, analyze and perform vector operations on the array, and slice numbers from the array. list_numbers = [[12, 23, -45], [18, -77, -44]] Using NumPy, create an array from the list. Write a code to return all the negative numbers in the list.  Using NumPy, write code to multiply each element in the array you created in question 1 by 2. Create a new variable for this array.  Write code to calculate the sum of the numbers on axis-1 of the array you created in question 2.  Write code to calculate the sum of numbers on axis-0 of the array you created in question 2.  Using the NumPy arange() function, create a NumPy array of numbers from 0 to 99. The shape of the array must be (2, 5, 10).  Write code to slice row [50, 51, 52, 53, 54, 55, 56, 57, 58, 59] from the array above (question 5).  Let’s analyze the array you created in question 1 further. How many numbers in row 1 are greater than the numbers in row 2?

In [2]:
import numpy as np

In [3]:
l = [[12,23,-45],[18,-77,-44]]

In [4]:
arr = np.array(l)
arr

array([[ 12,  23, -45],
       [ 18, -77, -44]])

In [5]:
y = np.where(arr[0,::1] > arr[1,::1])
len(y)

1

In [13]:
first_row = arr[0]
second_row = arr[1]
grater_c = np.greater(first_row,second_row)
grater_c = np.sum(grater_c)
grater_c # sum only sums true value

1

In [75]:
k = np.reshape(arr,(1,6))
k.shape
k

array([[ 12,  23, -45,  18, -77, -44]])

In [62]:
k = k.tolist()

In [63]:
k

[12, 23, -45, 18, -77, -44]

In [14]:
b = list()
for i in range(len(k)):
    if k[i] < 0:
        b.append(k[i])

        

In [15]:
b

[-45, -77, -44]

In [45]:
modi_arr = np.array(b)

In [46]:
modi_arr

array([-45, -77, -44])

In [52]:
multi_2 = modi_arr *2
k = multi_2
k.shape

(3,)

In [51]:
m = np.sum(multi_2,axis = 0)
m

-332

In [27]:
sum_ar = np.sum(multi_2,axis=0)

In [22]:
sum_ar

-332

In [85]:
aran = np.arange(0,100,1)

In [86]:
aran

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [84]:
aran.size

99

In [88]:
re_sp = np.reshape(aran,(2,5,10))
re_sp

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]])

In [91]:
re_sp[1,0,::1]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])