# day6

In [ ]:
In this challenge, your task is to create a NumPy array from a list of strings.
This particular challenge aims to assess your proficiency in generating arrays 
and manipulating array data types as a means of enhancing data processing flexibility.
list_str = ["23", "12", "90", "28", "30"] Create a NumPy array with the list above.
Calculate the standard deviation of the array.  Write a code to change the data type of
the array you created in question one (1) to a floating data type. Save this as a new variable.
Write a code to return the sum of values [90.0, 28.0, 30.0] from the array you just created in
question (3).  Create a 2-dimensional array of random integers from 0 to 100 with the shape (5, 5).
Use the array to find the minimum and maximum values, as well as the mean and standard deviation. 
Ensure that the results are reproducible.  Below are two arrays:  first_names = ["John", " Kenny"] 
last_names = ["Smith", " Sakula"] Using NumPy’s char.join() function, create two arrays by 
joining the first name with the last name. Your first array should be: array(['John', 'Smith'],
dtype='U6'). Your second array should be: array(['Kenny', 'Sakula'], dtype='U6').

In [1]:
import numpy as np

In [2]:
list_str = ["23", "12", "90", "28", "30"]

In [5]:
l1 = np.array(list_str, dtype= int)

In [6]:
l1

array([23, 12, 90, 28, 30])

In [7]:
sd = np.std(l1)

In [8]:
sd

27.419700946582186

In [16]:
l2 = np.array(list_str,dtype = float)

In [17]:
l2

array([23., 12., 90., 28., 30.])

In [18]:
l2 = l1.astype(float)

In [19]:
l2

array([23., 12., 90., 28., 30.])

In [20]:
n_a = np.sum(l2[2::1])

In [21]:
n_a

148.0

In [22]:
rng = np.random.default_rng(seed = 44)
arr_r = rng.integers(0,100,(5,5))

In [24]:
arr_r

array([[66, 12, 81, 25, 66],
       [40,  8, 96, 53, 16],
       [99, 85,  1, 16, 10],
       [33, 40, 67, 73, 61],
       [44, 95, 37, 41, 40]], dtype=int64)

In [25]:
maxi = np.max(arr_r)

In [26]:
maxi

99

In [27]:
mini = np.min(arr_r)

In [28]:
mini

1

In [29]:
mn = np.mean(arr_r)

In [30]:
mn

48.2

In [31]:
sd = np.std(arr_r)

In [32]:
sd

29.0709476969706

In [33]:
first_names = ["John", " Kenny"]
last_names = ["Smith", " Sakula"]

In [50]:
full_name = np.array([first_names,last_names])
full_name

array([['John', ' Kenny'],
       ['Smith', ' Sakula']], dtype='<U7')

In [61]:
full_name1 = full_name[:2:1,0]
full_name2 = full_name[:2:1,1]

In [62]:
full_name1

array(['John', 'Smith'], dtype='<U7')

In [63]:
full_name2

array([' Kenny', ' Sakula'], dtype='<U7')