# day8

In [2]:
import numpy as np

In [3]:
rng = np.random.default_rng(44)

In [4]:
arr = rng.integers(0,20,(10))

In [5]:
arr

array([13,  2, 16,  5, 13,  8,  1, 19, 10,  3], dtype=int64)

In [6]:
arr2 = np.array([arr[2],arr[4],arr[7]])

In [7]:
arr2

array([16, 13, 19], dtype=int64)

In [8]:
My_list = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]
arr3 = np.array(My_list)
arr3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [9]:
arr4 = np.reshape(arr3,(3,5))

In [10]:
arr4

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [11]:
arr5 = np.array([arr4[0,2],arr4[0,4],arr4[1,2]])

In [12]:
arr5.tolist()

[3, 5, 8]

In [13]:
arr5.ndim

1

In [14]:
arr5.shape


(3,)

In [15]:
lis1 = [[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]]
arr6 = np.array(lis1)

In [16]:
arr6

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]])

In [17]:
arr7 = np.array([arr6[0,0,3], arr6[0,1,2], arr6[0,2,4]])

In [18]:
arr7

array([ 4,  8, 15])

In [20]:
type(print(arr7))

[ 4  8 15]


NoneType