# day9

In [1]:
import numpy as np

In [2]:
nums = [12,4,6,7,9,19,21,67,8]

In [3]:
arr = np.array(nums)

In [4]:
arr

array([12,  4,  6,  7,  9, 19, 21, 67,  8])

In [5]:
mini = np.min(nums)

In [6]:
mini

4

In [9]:
maxi_indx = np.where(arr == np.max(arr))

In [28]:
maxi_indx

(array([7], dtype=int64),)

In [ ]:
#argmax method

In [30]:
m = np.argmax(arr)
m

7

In [14]:
avg_min_max = (np.max(arr) + np.min(arr))/2

In [15]:
avg_min_max

35.5

In [16]:
mn = np.mean(arr)

In [21]:
md = np.median(arr)
md

9.0

In [18]:
sd = np.std(arr)

In [19]:
arng = np.sort(arr)

In [20]:
arng

array([ 4,  6,  7,  8,  9, 12, 19, 21, 67])

In [25]:
arr_q1 = arr[:4:1]
q1_md = np.median(arr_q1)
q1_md

6.5

In [27]:
arr_q2 = arr[5::1]
q2_md = np.median(arr_q2)
q2_md

20.0

In [31]:
outlier = [x for x in arng if x<q1_md or x>q2_md]

In [32]:
outlier

[4, 6, 21, 67]

In [33]:
#alternet approch

In [34]:
sorted_array = np.sort(arr)

In [40]:
def cal_outlier(array):
    q1 = np.percentile(sorted_array,25)
    q3 = np.percentile(sorted_array,75)
    iqr = q3 - q1
    lower_bound = q1 - 1.5*iqr
    upper_bound = q3 + 1.5*iqr
    outlier = [x for x in sorted_array if x<lower_bound or x>upper_bound]
    return outlier,q1,q3,lower_bound,upper_bound

cal_outlier(sorted_array)

([67], 7.0, 19.0, -11.0, 37.0)